<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/RequestResponse" xmlns:tns="http://www.example.org/RequestResponse" elementFormDefault="qualified">

    <element name="Num1" type="string"></element>

    <element name="Num2" type="string"></element>

    <element name="Result" type="int"></element>

    <element name="Request" type="tns:RequestType"></element>
    
    <element name="Response" type="tns:ResponseType"></element>
    
    <complexType name="RequestType">
    	<sequence>
    		<element ref="tns:Num1"></element>
    		<element ref="tns:Num2"></element>
    	</sequence>
    </complexType>

    <complexType name="ResponseType">
    	<sequence>
    		<element ref="tns:Result"></element>
    	</sequence>
    </complexType>
</schema>